// ─── PRINTABLE COACH REPORT ───────────────────────────────────────────────────
// Builds a self-contained match report — full stats plus the AI coaching
// analysis — and hands it to the browser's print dialog, where the phone offers
// "Save as PDF" / AirPrint. Rendered into the live document behind an
// @media print rule (see mobileTheme.js) rather than a popup or iframe, which
// is the reliable path inside an installed PWA.
import {
  MATCH_STAT_ROWS, SHOT_GROUPS, formatStat, shotGroupTotal,
} from "./matchStats.js";

const esc = (s) => String(s ?? "")
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
  .replace(/"/g, "&quot;");

const row = (left, label, right, strong = false) => `
  <tr${strong ? ' class="strong"' : ""}>
    <td class="v left">${esc(left)}</td>
    <td class="lbl">${esc(label)}</td>
    <td class="v right">${esc(right)}</td>
  </tr>`;

function shotSection(stats, title, outcome) {
  const rows = SHOT_GROUPS
    .map(g => ({ label: g.label, a: shotGroupTotal(stats.p1, g, outcome), b: shotGroupTotal(stats.p2, g, outcome) }))
    .filter(r => r.a || r.b);
  if (!rows.length) return "";
  const totalA = rows.reduce((s, r) => s + r.a, 0);
  const totalB = rows.reduce((s, r) => s + r.b, 0);
  return `
    <h3>${esc(title)}</h3>
    <table>${rows.map(r => row(r.a, r.label, r.b)).join("")}${row(totalA, "Total", totalB, true)}</table>`;
}

function analysisSection(analysis) {
  if (!analysis) return "";
  const parts = [];
  if (analysis.matchSummary) parts.push(`<p>${esc(analysis.matchSummary)}</p>`);
  const findings = (analysis.criticalFindings || [])
    .map(f => (typeof f === "string" ? f : f.finding)).filter(Boolean);
  if (findings.length) {
    parts.push(`<h3>Findings</h3><ul>${findings.map(f => `<li>${esc(f)}</li>`).join("")}</ul>`);
  }
  const strengths = (analysis.strengthsToReinforce || []).filter(Boolean);
  if (strengths.length) {
    parts.push(`<h3>Strengths to reinforce</h3><ul>${strengths.map(s => `<li>${esc(s)}</li>`).join("")}</ul>`);
  }
  for (const [key, title] of [
    ["serveAnalysis", "Serve"],
    ["rallyPatternAnalysis", "Rally patterns"],
    ["shotBreakdownInsights", "Shot patterns"],
  ]) {
    if (analysis[key]) parts.push(`<h3>${title}</h3><p>${esc(analysis[key])}</p>`);
  }
  const cleared = (analysis.resolvedPriorities || [])
    .map(p => (typeof p === "string" ? { priority: p } : p)).filter(p => p?.priority);
  if (cleared.length) {
    parts.push(`<h3>Cleared from the focus list</h3><ul>${cleared
      .map(p => `<li><b>${esc(p.priority)}</b>${p.evidence ? ` — ${esc(p.evidence)}` : ""}</li>`).join("")}</ul>`);
  }
  if (!parts.length) return "";
  return `<section class="ai"><h2>AI coaching analysis</h2>${parts.join("")}</section>`;
}

// Returns the report body as an HTML string (also handy for tests/other sinks).
export function buildReportHtml({ match, stats, analysis }) {
  const p1 = match.valissaName || "Valissa";
  const p2 = match.opponentName || "Opponent";
  const score = (match.setScores?.p1 || [])
    .map((s, i) => `${s}-${match.setScores?.p2?.[i] ?? "?"}`).join(", ");
  const date = match.matchStartTime
    ? new Date(match.matchStartTime).toLocaleDateString("en-AU", { day: "numeric", month: "long", year: "numeric" })
    : "";
  const meta = [date, match.durationMin ? `${match.durationMin} min` : null]
    .filter(Boolean).join(" · ");

  const statRows = MATCH_STAT_ROWS
    .filter(r => stats.hasLog || !r.label.includes("Touches"))
    .map(r => {
      const left = formatStat(r.kind, r.get(stats.p1));
      const right = formatStat(r.kind, r.get(stats.p2));
      return left === "—" && right === "—" ? "" : row(left, r.label, right);
    }).join("");

  const shots = stats.hasLog ? [
    shotSection(stats, "Winners", "winners"),
    shotSection(stats, "Forced errors", "forced"),
    shotSection(stats, "Unforced errors", "unforced"),
  ].join("") : "";

  return `
    <header>
      <h1>${esc(p1)} vs ${esc(p2)}</h1>
      <div class="sub">${esc(match.whoWonMatch === 1 ? "Win" : "Loss")}${score ? ` ${esc(score)}` : ""}${meta ? ` · ${esc(meta)}` : ""}</div>
    </header>
    <section>
      <h2>Match stats</h2>
      <table class="head"><tr><th class="left">${esc(p1)}</th><th></th><th class="right">${esc(p2)}</th></tr></table>
      <table>${statRows}</table>
    </section>
    ${shots ? `<section><h2>Shot stats</h2>${shots}</section>` : ""}
    ${analysisSection(analysis)}
    <footer>Generated by Valissa's Tracker</footer>`;
}

// Mounts the report, prints, then cleans up. Returns true if it printed.
export function printReport({ match, stats, analysis }) {
  if (typeof document === "undefined" || typeof window.print !== "function") return false;
  const host = document.createElement("div");
  host.className = "print-root";
  host.innerHTML = buildReportHtml({ match, stats, analysis });
  document.body.appendChild(host);
  const cleanup = () => {
    if (host.parentNode) host.parentNode.removeChild(host);
    window.removeEventListener("afterprint", cleanup);
  };
  window.addEventListener("afterprint", cleanup);
  try {
    window.print();
  } finally {
    // Safari never fires afterprint in some standalone modes — belt and braces.
    setTimeout(cleanup, 1000);
  }
  return true;
}
